name: flutter_timer
description: Timer App 
version: 1.0.0+1 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  wave: ^0.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter 

flutter: 
  uses-material-design: true
